services:
  - type: web
    name: youtube-shorts-web
    runtime: python
    buildCommand: python3 -m pip install moviepy && python3 -m pip install -r requirements.txt
    startCommand: gunicorn webserver.app:app --bind 0.0.0.0:$PORT
    envVars:
    - key: GOOGLE_API_KEY
        value: ""
      - key: YOUTUBE_API_KEY
        value: ""
      - key: TELEGRAM_BOT_TOKEN
        value: ""
      - key: SHEETS_ID
        value: ""
      - key: OPENAI_API_KEY
        value: ""
      - key: PEXELS_API_KEY
        value: ""
    
  - type: worker
    name: youtube-shorts-worker
    env: python
    repo: https://github.com/your-username/your-repo-name
    branch: main
    buildCommand: python3 -m pip install moviepy && python3 -m pip install -r requirements.txt
    startCommand: python -m worker.main
    autoDeploy: true
    envVars:
      - key: GOOGLE_API_KEY
        value: ""
      - key: YOUTUBE_API_KEY
        value: ""
      - key: TELEGRAM_BOT_TOKEN
        value: ""
      - key: SHEETS_ID
        value: ""
      - key: OPENAI_API_KEY
        value: ""
      - key: PEXELS_API_KEY
        value: ""
